---

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "{{ docker_compose_path }}/docker-compose-{{ docker_compose_version }}"
    owner: root
    group: docker
    mode: 0775
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"

- name: Create symlink to docker-compose
  file:
    path: "{{ docker_compose_path }}/docker-compose"
    src: "{{ docker_compose_path }}/docker-compose-{{ docker_compose_version }}"
    owner: root
    group: docker
    mode: 0775
    state: link
