---

- import_tasks: install_docker.yml
  tags:
    - install

- import_tasks: install_docker-compose.yml
  tags:
    - install
  when: docker_compose_install|bool

- name: Flush handlers
  meta: flush_handlers

